# Generated by Django 5.0.4 on 2024-04-04 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('due_date', models.DateField(default=datetime.date.today, null=True)),
                ('completed', models.BooleanField(default=None)),
            ],
        ),
    ]
